import type { Product, Review } from "./types"

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear audio with our premium wireless headphones featuring active noise cancellation and 30-hour battery life.",
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviewCount: 124,
    images: ["/assets/Products/Headphones/headPhone1.jpg", "/assets/Products/Headphones/headPhone2.jpg", "/assets/Products/Headphones/headPhone3.jpg", "/assets/Products/Headphones/headPhone4.jpg"],
    category: "Electronics",
    brand: "AudioTech",
    inStock: true,
    badge: "Best Seller",
    stockCount: 15,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "White", value: "#FFFFFF" },
        { name: "Blue", value: "#3B82F6" },
      ],
    },
    features: [
      "Active Noise Cancellation",
      "30-hour battery life",
      "Quick charge (15 min = 3 hours)",
      "Premium leather cushions",
    ],
    specifications: {
      "Driver Size": "40mm",
      "Frequency Response": "20Hz - 20kHz",
      Impedance: "32 Ohm",
      Weight: "250g",
    },
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    description:
      "Track your fitness goals with this advanced smartwatch featuring heart rate monitoring, GPS, and 7-day battery life.",
    price: 199,
    originalPrice: 249,
    rating: 4.6,
    reviewCount: 89,
 images: [
    "/assets/Products/Watches/watch1.jpg",
    "/assets/Products/Watches/watch1-1.jpg",
    "/assets/Products/Watches/watch1-2.jpg",
  ],    category: "Wearables",
    brand: "FitTech",
    inStock: true,
    stockCount: 8,
    badge: "New",
    variants: {
      sizes: ["38mm", "42mm", "46mm"],
      colors: [
        { name: "Space Gray", value: "#4A5568" },
        { name: "Rose Gold", value: "#ED8936" },
        { name: "Silver", value: "#E2E8F0" },
      ],
    },
    features: ["Heart Rate Monitoring", "GPS Tracking", "Water Resistant (50m)", "7-day battery life"],
    specifications: {
      Display: "1.4 inch AMOLED",
      Battery: "7 days typical use",
      "Water Rating": "5ATM",
      Connectivity: "Bluetooth 5.0",
    },
  },
  {
    id: 3,
    name: "Minimalist Desk Lamp",
    description:
      "Illuminate your workspace with this sleek, adjustable LED desk lamp featuring touch controls and wireless charging base.",
    price: 79,
    originalPrice: 99,
    rating: 4.9,
    reviewCount: 156,
    images: [
  "/assets/Products/DeskLamp/desklamp1.jpg",
  "/assets/Products/DeskLamp/desklamp1-1.jpg",
  "/assets/Products/DeskLamp/desklamp1-2.jpg",
  "/assets/Products/DeskLamp/desklamp1-3.jpg" // <- Assuming you meant a 4th image (can be updated or removed)
],
    category: "Home & Garden",
    brand: "LightCraft",
    inStock: true,
    badge: "Sale",
    stockCount: 23,
    variants: {
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Black", value: "#000000" },
        { name: "Wood", value: "#8B4513" },
      ],
    },
    features: ["Touch Controls", "Wireless Charging Base", "Adjustable Brightness", "Memory Function"],
    specifications: {
      Power: "12W LED",
      "Color Temperature": "3000K-6500K",
      Charging: "10W Wireless",
      Material: "Aluminum Alloy",
    },
  },
  {
    id: 4,
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt with a modern fit. Perfect for everyday wear.",
    price: 29,
    originalPrice: 39,
    rating: 4.7,
    reviewCount: 203,
    images: [
  "/assets/Products/mens's wear/mens1.jpg",
  "/assets/Products/mens's wear/mens1-1.jpg",

],
    category: "Fashion",
    brand: "EcoWear",
    inStock: true,
    badge: "Eco-Friendly",
    stockCount: 45,
    variants: {
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Black", value: "#000000" },
        { name: "Navy", value: "#1E3A8A" },
        { name: "Gray", value: "#6B7280" },
      ],
    },
    features: ["100% Organic Cotton", "Pre-shrunk", "Tagless Design", "Machine Washable"],
    specifications: {
      Material: "100% Organic Cotton",
      Weight: "180 GSM",
      Fit: "Regular",
      Care: "Machine Wash Cold",
    },
  },
  {
    id: 5,
    name: "Professional Camera Lens",
    description:
      "High-quality 50mm prime lens perfect for portrait photography with beautiful bokeh and sharp details.",
    price: 599,
    originalPrice: 699,
    rating: 4.9,
    reviewCount: 67,
    images: [
  "/assets/Products/cameras/lens4.jpg",
  "/assets/Products/cameras/lens4-1.jpg",
  "/assets/Products/cameras/lens4-2.jpg",
],
    category: "Electronics",
    brand: "LensMaster",
    inStock: false,
    badge: "Limited Stock",
    stockCount: 0,
    variants: {
      colors: [{ name: "Black", value: "#000000" }],
    },
    features: ["f/1.4 Maximum Aperture", "Weather Sealed", "Silent Autofocus", "Professional Grade"],
    specifications: {
      "Focal Length": "50mm",
      Aperture: "f/1.4 - f/16",
      Mount: "Universal",
      Weight: "680g",
    },
  },
  {
    id: 6,
    name: "Ergonomic Office Chair",
    description: "Premium ergonomic office chair with lumbar support, adjustable height, and breathable mesh back.",
    price: 349,
    originalPrice: 449,
    rating: 4.5,
    reviewCount: 91,
    images: [
  "/assets/Products/Chairs/Chair1.jpg"],
    category: "Home & Garden",
    brand: "ComfortPro",
    inStock: true,
    badge: "Best Seller",
    stockCount: 12,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "Gray", value: "#6B7280" },
        { name: "White", value: "#FFFFFF" },
      ],
    },
    features: ["Lumbar Support", "Adjustable Height", "Breathable Mesh", "360° Swivel"],
    specifications: {
      "Max Weight": "150kg",
      "Height Range": "42-52cm",
      Material: "Mesh & Steel",
      Warranty: "5 Years",
    },
  },
   {
    id: 7,
    name: "Ultra HD 4K Smart TV",
    description:
      "Enjoy cinematic viewing with this 55-inch Ultra HD 4K Smart TV featuring HDR10+, built-in streaming apps, and voice control.",
    price: 799,
    originalPrice: 999,
    rating: 4.7,
    reviewCount: 132,
    images: [
  "/assets/Products/TV/TV1.jpg",
  "/assets/Products/TV/TV1-1.jpg",
  "/assets/Products/TV/TV1-2.jpg",
  "/assets/Products/TV/TV1-3.jpg"
],
    category: "Electronics",
    brand: "VisionX",
    inStock: true,
    badge: "New",
    stockCount: 9,
    variants: {
      sizes: ["43 inch", "55 inch", "65 inch"],
      colors: [{ name: "Black", value: "#000000" }],
    },
    features: [
      "Ultra HD 4K Resolution",
      "HDR10+",
      "Built-in Streaming Apps",
      "Voice Control with Assistant",
    ],
    specifications: {
      Display: "55 inch LED",
      Resolution: "3840x2160",
      "Refresh Rate": "120Hz",
      Connectivity: "HDMI x3, USB x2, Wi-Fi",
    },
  },
  {
    id: 8,
    name: "Smart Air Purifier",
    description:
      "Breathe cleaner air with this smart purifier featuring HEPA filter, real-time air quality monitoring, and app control.",
    price: 149,
    originalPrice: 199,
    rating: 4.8,
    reviewCount: 104,
    images: ["/assets/Products/Air Freshner/AirFreshner1.jpg"],
    category: "Home & Garden",
    brand: "PureAir",
    inStock: true,
    badge: "Best Seller",
    stockCount: 18,
    variants: {
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Charcoal", value: "#2D3748" },
      ],
    },
    features: [
      "True HEPA Filtration",
      "Smart App Control",
      "Real-time Air Quality Display",
      "Quiet Night Mode",
    ],
    specifications: {
      Coverage: "450 sq.ft.",
      NoiseLevel: "25 dB (Low)",
      FilterLife: "6 Months",
      Connectivity: "Wi-Fi, Bluetooth",
    },
  },
  {
    id: 9,
    name: "Gaming Mechanical Keyboard",
    description:
      "Dominate your game with this RGB-backlit mechanical keyboard featuring tactile switches and programmable macros.",
    price: 119,
    originalPrice: 149,
    rating: 4.6,
    reviewCount: 75,
    images: ["/assets/Products/Keyboard/keyboard1.jpg", "/assets/Products/Keyboard/keyboard1-1.jpg" ,"/assets/Products/Keyboard/keyboard1-2.jpg"],
    category: "Electronics",
    brand: "KeyForge",
    inStock: true,
    badge: "New",
    stockCount: 30,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "White", value: "#FFFFFF" },
      ],
    },
    features: [
      "Mechanical Tactile Switches",
      "Custom RGB Lighting",
      "Programmable Macros",
      "Detachable USB-C Cable",
    ],
    specifications: {
      Layout: "87-key TKL",
      SwitchType: "Blue Tactile",
      Connectivity: "USB-C Wired",
      Weight: "980g",
    },
  },
  {
    id: 10,
    name: "Hydrating Facial Serum",
    description:
      "Revitalize your skin with our lightweight facial serum enriched with hyaluronic acid and vitamin C for a radiant glow.",
    price: 45,
    originalPrice: 60,
    rating: 4.9,
    reviewCount: 211,
    images: ["assets/Products/FacialSerum/serum1.jpg"],
    category: "Beauty & Health",
    brand: "GlowSkin",
    inStock: true,
    badge: "Best Seller",
    stockCount: 34,
    variants: {
      sizes: ["30ml", "50ml"],
      colors: [{ name: "Transparent", value: "#F0F0F0" }],
    },
    features: [
      "Hyaluronic Acid + Vitamin C",
      "Non-greasy formula",
      "Dermatologist Tested",
      "Cruelty-Free",
    ],
    specifications: {
      Volume: "30ml",
      SkinType: "All types",
      ShelfLife: "24 Months",
      Usage: "AM & PM",
    },
  },
  {
    id: 11,
    name: "Remote Control Off-Road Truck",
    description:
      "Conquer any terrain with this rugged remote control truck featuring 4x4 drive, shock suspension, and long-range remote.",
    price: 89,
    originalPrice: 119,
    rating: 4.8,
    reviewCount: 147,
    images: ["/assets/Products/Off Road Truck/ORTruck1.jpg" ,"/assets/Products/Off Road Truck/ORTruck1-1.jpg","/assets/Products/Off Road Truck/ORTruck1-2.jpg"],
    category: "Toys & Games",
    brand: "TurboPlay",
    inStock: true,
    badge: "New",
    stockCount: 20,
    variants: {
      colors: [
        { name: "Red", value: "#EF4444" },
        { name: "Green", value: "#10B981" },
        { name: "Camo", value: "#6B705C" },
      ],
    },
    features: [
      "4x4 Off-Road Drive",
      "Shockproof Suspension",
      "2.4GHz Long-Range Remote",
      "Rechargeable Battery",
    ],
    specifications: {
      Scale: "1:16",
      Speed: "25 km/h",
      BatteryLife: "40 minutes",
      ChargingTime: "90 minutes",
    },
  },
  {
    id: 12,
    name: "Car Dashboard Phone Mount",
    description:
      "Secure your phone while driving with this 360° rotatable dashboard mount featuring one-touch lock and anti-slip grip.",
    price: 19,
    originalPrice: 29,
    rating: 4.5,
    reviewCount: 98,
    images: ["/assets/Products/phones/Phonestand1.jpg" ,"/assets/Products/phones/Phonestand1-1.jpg"],
    category: "Automotive",
    brand: "DriveMate",
    inStock: true,
    stockCount: 60,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "Gray", value: "#A0AEC0" },
      ],
    },
    features: [
      "One-Touch Lock Mechanism",
      "360° Rotation",
      "Anti-Slip Silicone Grip",
      "Universal Compatibility",
    ],
    specifications: {
      MountType: "Dashboard",
      Compatibility: "4.7–7 inch phones",
      Material: "ABS + Silicone",
      Weight: "120g",
    },
  },
   {
    id: 13,
    name: "Modern Wall Clock",
    description:
      "A stylish minimalist wall clock with silent movement, perfect for home or office decor.",
    price: 39,
    originalPrice: 59,
    rating: 4.7,
    reviewCount: 102,
    images: ["/assets/Products/Watches/clock1.jpg"],
    category: "Home & Garden",
    brand: "DecoTime",
    inStock: true,
    stockCount: 28,
    variants: {
      colors: [
        { name: "Matte Black", value: "#1F2937" },
        { name: "Rose Gold", value: "#B76E79" },
        { name: "Ivory White", value: "#F9FAFB" },
      ],
    },
    features: ["Silent Sweep Movement", "Easy Wall Mount", "Durable Build", "Battery Operated"],
    specifications: {
      Diameter: "12 inches",
      Movement: "Quartz",
      Power: "1x AA Battery (not included)",
      Material: "Metal & Glass",
    },
  },
  {
    id: 14,
    name: "Leather RFID Wallet",
    description:
      "Slim and secure genuine leather wallet with RFID-blocking technology to protect your cards.",
    price: 49,
    originalPrice: 69,
    rating: 4.8,
    reviewCount: 175,
    images: [
  "/assets/Products/mens's wear/Wallet1.jpg",
  "/assets/Products/mens's wear/Wallet1-1.jpg",
"/assets/Products/mens's wear/Wallet1-2.jpg",
],
    category: "Fashion",
    brand: "SecureStyle",
    inStock: true,
    stockCount: 35,
    variants: {
      colors: [
        { name: "Brown", value: "#8B4513" },
        { name: "Black", value: "#000000" },
        { name: "Tan", value: "#D2B48C" },
      ],
    },
    features: ["RFID Blocking", "Genuine Leather", "Slim Design", "Fits 8 Cards"],
    specifications: {
      Material: "Genuine Leather",
      Size: "4.3 x 3.1 inches",
      Weight: "85g",
      Warranty: "2 Years",
    },
  },
  {
    id: 15,
    name: "Hardcover Puzzle Book Collection",
    description:
      "Challenge your mind with a beautifully bound puzzle book featuring over 300 brain teasers, riddles, and logic games.",
    price: 35,
    originalPrice: 45,
    rating: 4.9,
    reviewCount: 260,
    images: [
  "/assets/Products/Books/book1.jpg",
  "/assets/Products/Books/book1-1.png",
],
    category: "Books & Media",
    brand: "BrainFuel",
    inStock: true,
    stockCount: 40,
    variants: {
      colors: [
        { name: "Navy", value: "#1E3A8A" },
        { name: "Maroon", value: "#800000" },
      ],
    },
    features: [
      "Over 300 Unique Puzzles",
      "Hardcover Binding",
      "Mixed Difficulty Levels",
      "Includes Solutions",
    ],
    specifications: {
      Pages: "320",
      Language: "English",
      Dimensions: "6 x 9 inches",
      Cover: "Hardcover",
    },
  },
   {
    id: 16,
    name: "Adjustable Dumbbell Set",
    description:
      "Compact adjustable dumbbell set perfect for home workouts. Change weights with a simple dial system.",
    price: 249,
    originalPrice: 299,
    rating: 4.7,
    reviewCount: 134,
    images: ["/assets/Products/gym/dumbbell1.jpg"],
    category: "Sports",
    brand: "FlexFit",
    inStock: true,
    stockCount: 10,
    variants: {
      sizes: ["25lb", "50lb"],
      colors: [
        { name: "Black", value: "#000000" },
        { name: "Red", value: "#DC2626" },
      ],
    },
    features: [
      "Adjustable Weight Dial",
      "Anti-slip Grip",
      "Space-Saving Design",
      "Durable Steel Plates",
    ],
    specifications: {
      WeightRange: "5–50 lbs",
      Material: "Steel + Rubber",
      Mechanism: "Twist Lock",
      Warranty: "2 Years",
    },
  },
  {
    id: 17,
    name: "STEM Robot Kit for Kids",
    description:
      "Interactive robot building kit to teach kids coding, robotics, and engineering in a fun and creative way.",
    price: 89,
    originalPrice: 119,
    rating: 4.8,
    reviewCount: 112,
    images: ["/assets/Products/toys/toy1.jpg"],
    category: "Toys & Games",
    brand: "EduTech",
    inStock: true,
    stockCount: 18,
    variants: {
      colors: [
        { name: "Blue", value: "#3B82F6" },
        { name: "Orange", value: "#F97316" },
      ],
    },
    features: [
      "Build & Code Your Robot",
      "App-Controlled",
      "USB Rechargeable",
      "Ages 8+",
    ],
    specifications: {
      BatteryLife: "6 hours",
      Programming: "Block-Based (Scratch)",
      PartsCount: "300+ pieces",
      Material: "Plastic + Electronics",
    },
  },
  {
    id: 18,
    name: "Portable Car Vacuum Cleaner",
    description:
      "Clean your car on the go with this compact vacuum featuring a powerful motor, HEPA filter, and long cable.",
    price: 39,
    originalPrice: 59,
    rating: 4.6,
    reviewCount: 87,
    images: ["/assets/Products/Automotive/vaccum1.jpg"],
    category: "Automotive",
    brand: "AutoClean",
    inStock: true,
    stockCount: 25,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "Gray", value: "#6B7280" },
      ],
    },
    features: [
      "Strong Suction",
      "HEPA Filter",
      "16-ft Power Cord",
      "Compact Design",
    ],
    specifications: {
      Voltage: "12V DC",
      Power: "120W",
      Weight: "850g",
      Filter: "Washable HEPA",
    },
  },
  {
    id: 19,
    name: "Wireless Charging Stand",
    description:
      "Charge your devices quickly and neatly with this vertical wireless charging stand supporting fast charging and dual coils.",
    price: 29,
    originalPrice: 49,
    rating: 4.5,
    reviewCount: 142,
    images: ["/assets/Products/phones/WirelessCharger1.jpg"],
    category: "Electronics",
    brand: "VoltBase",
    inStock: true,
    stockCount: 40,
    variants: {
      colors: [
        { name: "Matte Black", value: "#1F2937" },
        { name: "White", value: "#FFFFFF" },
      ],
    },
    features: [
      "Fast Wireless Charging",
      "Dual Coil Vertical Design",
      "Case Friendly",
      "LED Indicator",
    ],
    specifications: {
      Output: "10W / 7.5W / 5W",
      Compatibility: "Qi-enabled Devices",
      Cable: "USB-C Included",
      Material: "ABS + Silicone",
    },
  },
  {
    id: 20,
    name: "Polarized Aviator Sunglasses",
    description:
      "Classic aviator sunglasses with polarized lenses for UV protection and anti-glare vision.",
    price: 59,
    originalPrice: 79,
    rating: 4.9,
    reviewCount: 204,
    images: ["/assets/Products/mens's wear/glasses1.jpg"],
    category: "Fashion",
    brand: "SunGuard",
    inStock: true,
    stockCount: 30,
    variants: {
      colors: [
        { name: "Gold Frame / Green Lens", value: "#D4AF37" },
        { name: "Silver Frame / Blue Lens", value: "#3B82F6" },
        { name: "Black Frame / Gray Lens", value: "#000000" },
      ],
    },
    features: [
      "UV400 Protection",
      "Polarized Lenses",
      "Scratch Resistant",
      "Unisex Design",
    ],
    specifications: {
      Frame: "Metal Alloy",
      Lens: "Polarized TAC",
      Width: "58mm",
      Warranty: "1 Year",
    },
  },
  {
    id: 21,
    name: "Stainless Steel Air Fryer",
    description:
      "Cook healthier meals with this stainless steel air fryer featuring a digital display and 7 preset cooking modes.",
    price: 129,
    originalPrice: 179,
    rating: 4.8,
    reviewCount: 192,
    images: ["/assets/Products/Home&Garden/Fryer1.jpg"],
    category: "Home & Garden",
    brand: "KitchenEase",
    inStock: true,
    badge: "Best Seller",
    stockCount: 22,
    variants: {
      sizes: ["4L", "6L"],
      colors: [
        { name: "Stainless Steel", value: "#D1D5DB" },
        { name: "Black", value: "#111827" },
      ],
    },
    features: [
      "Oil-Free Frying",
      "7 Cooking Presets",
      "Digital Touchscreen",
      "Dishwasher Safe Parts",
    ],
    specifications: {
      Capacity: "6 Liters",
      Power: "1700W",
      Voltage: "220-240V",
      Dimensions: "35 x 28 x 32 cm",
    },
  },
  {
    id: 22,
    name: "RGB Mechanical Gaming Keyboard",
    description:
      "Enhance your gameplay with this tactile mechanical keyboard featuring customizable RGB lighting and anti-ghosting keys.",
    price: 99,
    originalPrice: 129,
    rating: 4.7,
    reviewCount: 143,
    images: ["/assets/Products/Keyboard/keyboard1.jpg", "/assets/Products/Keyboard/keyboard1-1.jpg" ,"/assets/Products/Keyboard/keyboard1-2.jpg"],
    category: "Electronics",
    brand: "GamerForge",
    inStock: true,
    badge: "New",
    stockCount: 17,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "White", value: "#FFFFFF" },
      ],
    },
    features: [
      "Customizable RGB Lighting",
      "Mechanical Switches",
      "Anti-Ghosting",
      "Wrist Rest Included",
    ],
    specifications: {
      Layout: "104 Keys Full-Size",
      Connectivity: "USB Wired",
      CableLength: "1.8m",
      Compatibility: "Windows/Mac/Linux",
    },
  },
  
]

export const mockReviews: Review[] = [
  {
    id: 1,
    userId: 1,
    userName: "Sarah Johnson",
    rating: 5,
    comment:
      "Absolutely love these headphones! The sound quality is incredible and the noise cancellation works perfectly.",
    date: "2024-01-10",
    verified: true,
  },
  {
    id: 2,
    userId: 2,
    userName: "Mike Chen",
    rating: 4,
    comment: "Great product overall. Battery life is as advertised and very comfortable to wear for long periods.",
    date: "2024-01-08",
    verified: true,
  },
  {
    id: 3,
    userId: 3,
    userName: "Emily Rodriguez",
    rating: 5,
    comment: "Best purchase I've made this year. The build quality is excellent and the features are amazing.",
    date: "2024-01-05",
    verified: false,
  },
]
