import type { Product, Review } from "./types"

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear audio with our premium wireless headphones featuring active noise cancellation and 30-hour battery life.",
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviewCount: 124,
    images: ["🎧", "🎵", "🔊", "🎤"],
    category: "Electronics",
    brand: "AudioTech",
    inStock: true,
    stockCount: 15,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "White", value: "#FFFFFF" },
        { name: "Blue", value: "#3B82F6" },
      ],
    },
    features: [
      "Active Noise Cancellation",
      "30-hour battery life",
      "Quick charge (15 min = 3 hours)",
      "Premium leather cushions",
    ],
    specifications: {
      "Driver Size": "40mm",
      "Frequency Response": "20Hz - 20kHz",
      Impedance: "32 Ohm",
      Weight: "250g",
    },
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    description:
      "Track your fitness goals with this advanced smartwatch featuring heart rate monitoring, GPS, and 7-day battery life.",
    price: 199,
    originalPrice: 249,
    rating: 4.6,
    reviewCount: 89,
    images: ["⌚", "💓", "🏃", "📱"],
    category: "Wearables",
    brand: "FitTech",
    inStock: true,
    stockCount: 8,
    variants: {
      sizes: ["38mm", "42mm", "46mm"],
      colors: [
        { name: "Space Gray", value: "#4A5568" },
        { name: "Rose Gold", value: "#ED8936" },
        { name: "Silver", value: "#E2E8F0" },
      ],
    },
    features: ["Heart Rate Monitoring", "GPS Tracking", "Water Resistant (50m)", "7-day battery life"],
    specifications: {
      Display: "1.4 inch AMOLED",
      Battery: "7 days typical use",
      "Water Rating": "5ATM",
      Connectivity: "Bluetooth 5.0",
    },
  },
  {
    id: 3,
    name: "Minimalist Desk Lamp",
    description:
      "Illuminate your workspace with this sleek, adjustable LED desk lamp featuring touch controls and wireless charging base.",
    price: 79,
    originalPrice: 99,
    rating: 4.9,
    reviewCount: 156,
    images: ["💡", "🏢", "✨", "🔌"],
    category: "Home & Garden",
    brand: "LightCraft",
    inStock: true,
    stockCount: 23,
    variants: {
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Black", value: "#000000" },
        { name: "Wood", value: "#8B4513" },
      ],
    },
    features: ["Touch Controls", "Wireless Charging Base", "Adjustable Brightness", "Memory Function"],
    specifications: {
      Power: "12W LED",
      "Color Temperature": "3000K-6500K",
      Charging: "10W Wireless",
      Material: "Aluminum Alloy",
    },
  },
  {
    id: 4,
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt with a modern fit. Perfect for everyday wear.",
    price: 29,
    originalPrice: 39,
    rating: 4.7,
    reviewCount: 203,
    images: ["👕", "🌱", "👔", "🧵"],
    category: "Fashion",
    brand: "EcoWear",
    inStock: true,
    stockCount: 45,
    variants: {
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Black", value: "#000000" },
        { name: "Navy", value: "#1E3A8A" },
        { name: "Gray", value: "#6B7280" },
      ],
    },
    features: ["100% Organic Cotton", "Pre-shrunk", "Tagless Design", "Machine Washable"],
    specifications: {
      Material: "100% Organic Cotton",
      Weight: "180 GSM",
      Fit: "Regular",
      Care: "Machine Wash Cold",
    },
  },
  {
    id: 5,
    name: "Professional Camera Lens",
    description:
      "High-quality 50mm prime lens perfect for portrait photography with beautiful bokeh and sharp details.",
    price: 599,
    originalPrice: 699,
    rating: 4.9,
    reviewCount: 67,
    images: ["📷", "🔍", "🎯", "✨"],
    category: "Electronics",
    brand: "LensMaster",
    inStock: false,
    stockCount: 0,
    variants: {
      colors: [{ name: "Black", value: "#000000" }],
    },
    features: ["f/1.4 Maximum Aperture", "Weather Sealed", "Silent Autofocus", "Professional Grade"],
    specifications: {
      "Focal Length": "50mm",
      Aperture: "f/1.4 - f/16",
      Mount: "Universal",
      Weight: "680g",
    },
  },
  {
    id: 6,
    name: "Ergonomic Office Chair",
    description: "Premium ergonomic office chair with lumbar support, adjustable height, and breathable mesh back.",
    price: 349,
    originalPrice: 449,
    rating: 4.5,
    reviewCount: 91,
    images: ["🪑", "💼", "🏢", "⚙️"],
    category: "Home & Garden",
    brand: "ComfortPro",
    inStock: true,
    stockCount: 12,
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "Gray", value: "#6B7280" },
        { name: "White", value: "#FFFFFF" },
      ],
    },
    features: ["Lumbar Support", "Adjustable Height", "Breathable Mesh", "360° Swivel"],
    specifications: {
      "Max Weight": "150kg",
      "Height Range": "42-52cm",
      Material: "Mesh & Steel",
      Warranty: "5 Years",
    },
  },
]

export const mockReviews: Review[] = [
  {
    id: 1,
    userId: 1,
    userName: "Sarah Johnson",
    rating: 5,
    comment:
      "Absolutely love these headphones! The sound quality is incredible and the noise cancellation works perfectly.",
    date: "2024-01-10",
    verified: true,
  },
  {
    id: 2,
    userId: 2,
    userName: "Mike Chen",
    rating: 4,
    comment: "Great product overall. Battery life is as advertised and very comfortable to wear for long periods.",
    date: "2024-01-08",
    verified: true,
  },
  {
    id: 3,
    userId: 3,
    userName: "Emily Rodriguez",
    rating: 5,
    comment: "Best purchase I've made this year. The build quality is excellent and the features are amazing.",
    date: "2024-01-05",
    verified: false,
  },
]
